### PR TITLE
Chore/use info colors

### PR DESCRIPTION
**Pull request by xiduzo**
- Bumped package versions to be in line with the forked branch
- Make use of info colours according to https://wiki.info.nl/display/overall/huisstijl

### CODE REVIEW

**Review by dominikvrbic — APPROVED** [review]
looks good

**Comment by edgarvonk** [comment]
Screenshot 2022-12-07 at 11 47 36

Nice bright colours. :-) Just checking: is https://wiki.info.nl/display/overall/huisstijl really up to date? I think this may be quite outdated no? Maybe you can check with e.g. Myrte about this?

**Comment by edgarvonk** [comment]
As far as I know our INFO brand book is on: https://infonl.atlassian.net/wiki/spaces/IHS/pages/19726457/Branding+2022+Files+and+Templates (and then Sharepoint). I think https://wiki.info.nl/display/overall/huisstijl is heavily outdated and needs to be removed. I just sent a Slack msg to Myrte to confirm.

**Comment by edgarvonk** [comment]
Confirmed by Myrte. https://wiki.info.nl/display/overall/huisstijl is very very old and should not be used. https://infonl.atlassian.net/wiki/spaces/IHS/pages/19726457/Branding+2022+Files+and+Templates is the current one. Can you update the colours @xiduzo accordingly :-)

**Comment by xiduzo** [comment]
I could change the green color which is used. Unfortunately, the new branding guidelines do not have any other colors for the other segments 🤔

**Comment by edgarvonk** [comment]
> I could change the green color which is used. Unfortunately, the new branding guidelines do not have any other colors for the other segments 🤔

I know.. ;-) That's part of the reason why I did not bother with the INFO branding when creating this tech radar. I'll leave it up to you. Just updating the green might be nice. And you could check with Myrte maybe?

**Comment by edgarvonk** [comment]
@xiduzo what is the status and your plan for this PR now? Shall we discard it for now?

**Comment by edgarvonk** [comment]
Decided not to pursue this as the colours are ok like they are and the current INFO styleguide does not fit so well with the radar anyway. Updating deps will be done separately.

**Pull request closed without merging**
